### ISSUE TITLE
Typo in repo name

### ISSUE THREAD

**Issue by jlengstorf** [joshatoutthink/gastby-theme-blog-remix#2]
Thanks for submitting a theme! It looks like there's a typo in the repo name, though — you used "gastby" instead of "gatsby".

Do you mind renaming/republishing for consistency? Thanks!

**Comment by joshmkennedy** [comment]
> Thanks for submitting a theme! It looks like there's a typo in the repo name, though — you used "gastby" instead of "gatsby".
> 
> Do you mind renaming/republishing for consistency? Thanks!

Do I need to re submit or will the showcase theme repull my repo's name
